    timestamp: pd.DataFrame = field(default_factory=pd.DataFrame)
    attributes: pd.DataFrame = field(default_factory=pd.DataFrame)
    resource: pd.DataFrame = field(default_factory=pd.DataFrame)
    trace_id: pd.DataFrame = field(default_factory=pd.DataFrame)
    span_id: pd.DataFrame = field(default_factory=pd.DataFrame)
    severity_text: pd.DataFrame = field(default_factory=pd.DataFrame)
    severity_number: pd.DataFrame = field(default_factory=pd.DataFrame)
    body: pd.DataFrame = field(default_factory=pd.DataFrame)
    labels: pd.DataFrame = field(default_factory=pd.DataFrame)
    _index: np.array = field(init=False) 




from gui.pages.utils import create_upload_file_layout

app.layout = html.Div(
    [
        dcc.Location(id="url", refresh=False),
        create_upload_file_layout(),  # Thêm phần tải file vào layout
        html.Div(id="page-content"),
    ]
)


@callback(Output("page-content", "children"), [Input("url", "pathname")])
def display_page(pathname):
    if pathname == "/upload":
        return create_upload_file_layout()  # Hiển thị phần tải file trên trang /upload
    # Các trang khác...



    print("Uploaded Filenames:", uploaded_filenames)
    print("Uploaded File Contents:", uploaded_file_contents)





loi 
Traceback (most recent call last):
  File "/logai/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/logai/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/logai/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/logai/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/logai/venv/lib/python3.12/site-packages/dash/dash.py", line 1405, in dispatch
    ctx.run(
  File "/logai/venv/lib/python3.12/site-packages/dash/_callback.py", line 529, in add_context
    raise err
  File "/logai/venv/lib/python3.12/site-packages/dash/_callback.py", line 518, in add_context
    output_value = _invoke_callback(func, *func_args, **func_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/logai/venv/lib/python3.12/site-packages/dash/_callback.py", line 47, in _invoke_callback
    return func(*args, **kwargs)  # %% callback invoked %%
           ^^^^^^^^^^^^^^^^^^^^^
  File "/logai/gui/callbacks/clustering.py", line 180, in update_logline_list
    if len(data) > 0:
       ^^^^^^^^^
TypeError: object of type 'NoneType' has no len()





@callback(
    Output("file-select", "options"),
    Output("file-select", "value"),
    [Input("log-type-select", "value")],
)
def select_file(dataset_name):
    print(f"Dataset name received: {dataset_name}")  # Debug giá trị dataset_name
    options = []
    files = file_manager.uploaded_files()
    for filename in files:
        if dataset_name.lower() == "custom" or dataset_name.lower() in filename.lower():
            options.append({"label": filename, "value": filename})

    if len(options) > 0:
        return options, options[0]["value"]
    else:
        return options, ""

